In [23]:
# 1. Introduction to numpy( We use array instead of index)
import pandas as pd
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr + 5)
print(arr * 2)
print(np.mean(arr))
print(np.std(arr))

# Slicing array
subset = arr[2:6]
print("Original array:", arr)
print("sliced subset (from index 2 to 5):", subset)

[ 6  7  8  9 10]
[ 2  4  6  8 10]
3.0
1.4142135623730951
Original array: [1 2 3 4 5]
sliced subset (from index 2 to 5): [3 4 5]


In [81]:
arr2 = np.array([10,20,30,40,50,60,70,80,90])
print(arr2 + 5)
print(arr2 ** 2)
print(arr2 *2 )
print(np.mean(arr2))
print(np.std(arr2))

subset2 = arr2 [4:7]
print("original array:", arr2)
print("Slicied subset1 (from index 4 to 7):", subset2)

[15 25 35 45 55 65 75 85 95]
[ 100  400  900 1600 2500 3600 4900 6400 8100]
[ 20  40  60  80 100 120 140 160 180]
50.0
25.81988897471611
original array: [10 20 30 40 50 60 70 80 90]
Slicied subset1 (from index 4 to 7): [50 60 70]


In [85]:
# 2. Introduction to Pandas (here we use series with labeled axes or index instead od array)
series = pd.Series([10,20,30,40,50,60], index=['a','b','c','d','e','f'])
print(series)

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64


In [87]:
series = pd.Series([10,20,30,40,50,60], index=[1,2,3,4,5,6])
print(series)

1    10
2    20
3    30
4    40
5    50
6    60
dtype: int64


In [89]:
# Creating a DataFrame

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [24, 27, 22], 'City': ['NYC', 'LA', 'Chicago']}
df = pd.DataFrame(data)
print(df)


      Name  Age     City
0    Alice   24      NYC
1      Bob   27       LA
2  Charlie   22  Chicago


In [91]:
data1 = {'Name':['Koushik','Keerthan','Ravi'],'age':[24,27,38],'city': ['Chakkere','Haniyuru','Haniyuru']}
df = pd.DataFrame(data1)
print(df)

       Name  age      city
0   Koushik   24  Chakkere
1  Keerthan   27  Haniyuru
2      Ravi   38  Haniyuru


In [97]:
# Loading data
df =pd.read_csv('titanic passenger list.csv')

# 3. Data Frame operations are Sorting,  filtering, df.head, df.tal, df.describe, df.info
print(df.head(10))

   pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
5       1         1                              Anderson, Mr. Harry    male   
6       1         1                Andrews, Miss. Kornelia Theodosia  female   
7       1         0                           Andrews, Mr. Thomas Jr    male   
8       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female   
9       1         0                          Artagaveytia, Mr. Ramon    male   

     age  sibsp  parch    ticket      fare    cabin embarked boat   body  \
0  29.00      0      0     24160  211.3375 

In [101]:
print(df.describe())

            pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881138     0.498854     0.385027   
std       0.837836     0.486055    14.413493     1.041658     0.865560   
min       1.000000     0.000000     0.170000     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000  


In [103]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB
None


In [115]:
df_sorted = df.sort_values(by='age', ascending=True)
print(df_sorted)

      pclass  survived                                     name     sex   age  \
763        3         1  Dean, Miss. Elizabeth Gladys "Millvina"  female  0.17   
747        3         0  Danbom, Master. Gilbert Sigvard Emanuel    male  0.33   
1240       3         1          Thomas, Master. Assad Alexander    male  0.42   
427        2         1                Hamalainen, Master. Viljo    male  0.67   
1111       3         0           Peacock, Master. Alfred Edward    male  0.75   
...      ...       ...                                      ...     ...   ...   
1293       3         0        Williams, Mr. Howard Hugh "Harry"    male   NaN   
1297       3         0                   Wiseman, Mr. Phillippe    male   NaN   
1302       3         0                        Yousif, Mr. Wazli    male   NaN   
1303       3         0                    Yousseff, Mr. Gerious    male   NaN   
1305       3         0                    Zabour, Miss. Thamine  female   NaN   

      sibsp  parch         

In [119]:
df_filtered = df_sorted[(df_sorted['age'] >=20) & (df_sorted['age'] <=40)]
print(df_filtered)

      pclass  survived                                               name  \
1091       3         0                            Oreskovic, Miss. Marija   
883        3         0                             Jensen, Mr. Hans Peder   
633        3         0                         Andreasson, Mr. Paul Edvin   
673        3         0                                Betros, Mr. Tannous   
718        3         0                     Coelho, Mr. Domingos Fernandeo   
...      ...       ...                                                ...   
583        2         1  Watt, Mrs. James (Elizabeth "Bessie" Inglis Mi...   
497        2         0                          Maybery, Mr. Frank Hubert   
831        3         0                     Goodwin, Mr. Charles Frederick   
260        1         1                          Shutes, Miss. Elizabeth W   
406        2         0                              Faunthorpe, Mr. Harry   

         sex   age  sibsp  parch              ticket      fare cabin embark

In [137]:
count_rows = df_filtered.shape[0]
print("Total count of Age b/w 20 - 40 are:",count_rows)

Total count of Age b/w 20 - 40 are: 594


In [139]:
count_rows = df_sorted.shape[0]
print("Over all passengers are:",count_rows)

Over all passengers are: 1309


In [147]:
a=1300
b=594
c=a-b
print(f"Other than 20- 40 age passengers are:{c}")

Other than 20- 40 age passengers are:706


In [149]:
# 3.1 Dataframe operations
print(df['age'])

0       29.00
1        0.92
2        2.00
3       30.00
4       25.00
        ...  
1304    14.50
1305      NaN
1306    26.50
1307    27.00
1308    29.00
Name: age, Length: 1309, dtype: float64


In [151]:
print(df.loc[0])

pclass                                   1
survived                                 1
name         Allen, Miss. Elisabeth Walton
sex                                 female
age                                   29.0
sibsp                                    0
parch                                    0
ticket                               24160
fare                              211.3375
cabin                                   B5
embarked                                 S
boat                                     2
body                                   NaN
home.dest                     St Louis, MO
Name: 0, dtype: object


In [153]:
print(df.iloc[1:4])

   pclass  survived                                  name     sex    age  \
1       1         1        Allison, Master. Hudson Trevor    male   0.92   
2       1         0          Allison, Miss. Helen Loraine  female   2.00   
3       1         0  Allison, Mr. Hudson Joshua Creighton    male  30.00   

   sibsp  parch  ticket    fare    cabin embarked boat   body  \
1      1      2  113781  151.55  C22 C26        S   11    NaN   
2      1      2  113781  151.55  C22 C26        S  NaN    NaN   
3      1      2  113781  151.55  C22 C26        S  NaN  135.0   

                         home.dest  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  


In [165]:
original_row_count = df.shape[0]
print(original_row_count)

1309


In [161]:
# 4. Data manipulation and cleaning in pandas
# Handling missing data:

# Identify the missing values
print(df.isnull())

      pclass  survived   name    sex    age  sibsp  parch  ticket   fare  \
0      False     False  False  False  False  False  False   False  False   
1      False     False  False  False  False  False  False   False  False   
2      False     False  False  False  False  False  False   False  False   
3      False     False  False  False  False  False  False   False  False   
4      False     False  False  False  False  False  False   False  False   
...      ...       ...    ...    ...    ...    ...    ...     ...    ...   
1304   False     False  False  False  False  False  False   False  False   
1305   False     False  False  False   True  False  False   False  False   
1306   False     False  False  False  False  False  False   False  False   
1307   False     False  False  False  False  False  False   False  False   
1308   False     False  False  False  False  False  False   False  False   

      cabin  embarked   boat   body  home.dest  
0     False     False  False   True   

In [159]:
# Dropping missing values: using dropna() to remove rows with misiing values:
df_cleaning = df.dropna()
print(df_cleaning)

Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []


In [169]:
df_cleaned=df.dropna()
print(df_cleaned)

Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []


In [175]:
cleaned_rows_count=df_cleaned.shape[0]
print(cleaned_rows_count)

0


In [181]:
# To find how many rows dropped
rows_dropped = original_row_count - cleaned_rows_count
print(f"Number of rows dropped: {rows_dropped}")

Number of rows dropped: 1309


In [183]:
print(df)

      pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex    age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.00  

In [185]:
# Filling missing values fillna() o fill missing values with a specific value or method.
df_filled = df.fillna(0)  # Replace NaN with 0

In [193]:
# Condition-based filtering and selecting data: 
# Condition-Based Filtering: Use boolean conditions to filter rows.

filtered_df = df[df['age'] > 25]
print(filtered_df)

      pclass  survived                                  name     sex   age  \
0          1         1         Allen, Miss. Elisabeth Walton  female  29.0   
3          1         0  Allison, Mr. Hudson Joshua Creighton    male  30.0   
5          1         1                   Anderson, Mr. Harry    male  48.0   
6          1         1     Andrews, Miss. Kornelia Theodosia  female  63.0   
7          1         0                Andrews, Mr. Thomas Jr    male  39.0   
...      ...       ...                                   ...     ...   ...   
1299       3         0                   Yasbeck, Mr. Antoni    male  27.0   
1301       3         0                  Youseff, Mr. Gerious    male  45.5   
1306       3         0             Zakarian, Mr. Mapriededer    male  26.5   
1307       3         0                   Zakarian, Mr. Ortin    male  27.0   
1308       3         0                    Zimmerman, Mr. Leo    male  29.0   

      sibsp  parch  ticket      fare    cabin embarked boat   b

In [197]:
count_filtered_df = filtered_df.shape[0]
print(count_filtered_df)

603


In [201]:
# Grouping by Aggregating Data:
# Group by: Useful for performing aggregation operations on subsets of data.

grouped_df = df.groupby ('home.dest')['age'].mean()
print(grouped_df)

home.dest
?Havana, Cuba                          28.500000
Aberdeen / Portland, OR                26.000000
Albany, NY                             31.000000
Altdorf, Switzerland                   21.500000
Amenia, ND                             46.500000
                                         ...    
Worcester, England                     19.000000
Worcester, MA                          37.000000
Yoevil, England / Cottage Grove, OR    26.000000
Youngstown, OH                         40.750000
Zurich, Switzerland                    43.333333
Name: age, Length: 369, dtype: float64


In [205]:
# 5. Data Transformation with pandas
# Creating New Columns: You can create new columns based on existing ones.

df['agesquared'] =df['age']**2
print(df)

      pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex    age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.00  

In [209]:
# Column Operations: Perform operations on entire columns.
df['age'] = df['age']+1
print(df)

      pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex    age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  31.00  

In [211]:
# Merging and Joining DataFrames:
# Use merge() to join two DataFrames based on a common column.

df1 = pd.DataFrame({'ID': [1, 2, 3], 'Value': ['A', 'B', 'C']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Score': [90, 80, 70]})
merged_df = pd.merge(df1, df2, on='ID', how='inner')


In [213]:
print(merged_df)

   ID Value  Score
0   1     A     90
1   2     B     80
